# Generated by Django 2.2.12 on 2020-05-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_content', models.CharField(max_length=200)),
                ('observation_date', models.DateTimeField(verbose_name='observation date')),
            ],
        ),
    ]
